name: Publish Beta Docker Image

on:
    push:
        branches: ["staging"]

jobs:
    Publish-Docker-Image:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout the repo
              uses: actions/checkout@v4

            - name: Log in to Docker Hub
              uses: docker/login-action@v3
              with:
                  username: ${{ secrets.DOCKER_USERNAME }}
                  password: ${{ secrets.DOCKER_PASSWORD }}

            - name: Build Docker image
              run: |
                  VERSION=$(node -p "require('./package.json').version")
                  docker build -t beantech.azurecr.io/www.beenhamow.co.uk:beta-v$VERSION .
                  docker tag beantech.azurecr.io/www.beenhamow.co.uk:beta-v$VERSION beantech.azurecr.io/www.beenhamow.co.uk:beta

            - name: Push Docker images
              run: |
                  VERSION=$(node -p "require('./package.json').version")
                  docker push beantech.azurecr.io/www.beenhamow.co.uk:beta-v$VERSION
                  docker push beantech.azurecr.io/www.beenhamow.co.uk:beta
