name: Publish Production Docker Image

on:
    push:
        branches: ["production"]

jobs:
    Publish-Docker-Image:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout the repo
              uses: actions/checkout@v4

            - name: Log in to Docker Hub
              uses: docker/login-action@v3
              with:
                  username: ${{ secrets.DOCKER_USERNAME }}
                  password: ${{ secrets.DOCKER_PASSWORD }}

            - name: Build Docker image
              run: |
                  VERSION=$(node -p "require('./package.json').version")
                  docker build -t beenhamo/www.beenhamow.co.uk:$VERSION .
                  docker tag beenhamo/www.beenhamow.co.uk:$VERSION beenhamo/www.beenhamow.co.uk:latest

            - name: Push Docker images
              run: |
                  VERSION=$(node -p "require('./package.json').version")
                  docker push beenhamo/www.beenhamow.co.uk:$VERSION
                  docker push beenhamo/www.beenhamow.co.uk:latest
